### PR TITLE
Add ethan-max

### PR DESCRIPTION
**Pull request by ethan-max**

### CODE REVIEW

**Review by x0mmm — APPROVED** [review]

**Review by melanietimms — CHANGES_REQUESTED** [review]
You need a full stop!!!!

**Review by jparker1122 — COMMENTED** [review]
good

**Review by x0mmm — APPROVED** [review]

**Comment by apal-tafe** [comment]
good

**Review by apal-tafe — APPROVED** [review]
bad but good, no full stop still

**Review by melanietimms — APPROVED** [review]

**Pull request merged**
